controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\RecetasController::index

recetas:
    path:       /recetas/new
    controller: App\Controller\RecetasController::new

misRecetas:
    path:       /recetas/mis-recetas
    controller: App\Controller\RecetasController::misRecetas

app_logout:
    path: /logout
    methods: GET