controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

recetas:
    path:       /recetas/new
    controller: App\Controller\RecetasController::new

app_logout:
    path: /logout
    methods: GET